### PR TITLE
downgrade eslint to solve build errors in airbnb

### PR DESCRIPTION
**Pull request by nishantbisen09**

### CODE REVIEW

**Comment by CodingCreate101** [comment]
Do not merge without a successful deployment of preview . It doesn't work
image

**Comment by CodingCreate101** [comment]
You are merging things that are not actually solutions, this will lead to side effects in the application

**Comment by CodingCreate101** [comment]
Try all the solutions in a separate branch and test deploy them

**Comment by nishantbisen09** [comment]
Yeah I should do that

**Pull request merged**
